version: '3'

services:
  php:
    container_name: affirmations
    build:
      context: docker/php
    volumes:
      - ./:/var/www
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    ports:
      - '9010:9000'
    restart: always

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./var/log:/var/log
    depends_on:
      - php
    ports:
      - "8010:80"
    restart: always

